In [31]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


# ============================================================
# Task 1: Array Creation Shortcuts
# ============================================================
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers from 10 to 50
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# ============================================================
# Task 2: Indexing and Slicing with Arrays
# ============================================================
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# 2.1 Element at row 2, column 3
val2_1 = data[2, 3]

# 2.2 First row
row2_2 = data[0, :]

# 2.3 Last column
col2_3 = data[:, -1]

# 2.4 Rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Elements greater than 100
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


# ============================================================
# Task 3: Conditional Operations
# ============================================================
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

# 3.1 Replace values less than 10 with 0
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count even elements
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("even_count3_3:", even_count3_3)


# ============================================================
# Task 4: Aggregation Functions
# ============================================================
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])

# 4.1 Sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Standard deviation of entire array
std4_4 = np.std(arr4_1)

print("sum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)


# ============================================================
# Task 5: Reshaping and Flattening
# ============================================================
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

# 5.1 Reshape into 4x6
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into 2x3x4
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten back into 1D
flattened_arr5_4 = reshaped_arr5_2.flatten()

# Using ravel() as well
raveled_arr5_4 = reshaped_arr5_2.ravel()

print("reshaped_arr5_2:\n", reshaped_arr5_2)
print("reshaped_arr5_3:\n", reshaped_arr5_3)
print("flattened_arr5_4:", flattened_arr5_4)
print("raveled_arr5_4:", raveled_arr5_4)


# ============================================================
# Task 6: Broadcasting
# ============================================================
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add vector to each row
result6_2 = arr6_1 + vector

print("result6_1:\n", result6_1)
print("result6_2:\n", result6_2)


# ============================================================
# Task 7: Copying vs. Viewing Arrays
# ============================================================
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view
view_arr7 = original_arr7[:]

# Modify view
view_arr7[0] = 99

print("View:", view_arr7)
print("Original after view change:", original_arr7)

# 7.2 Create a copy
copy_arr7 = original_arr7.copy()

# Modify copy
copy_arr7[-1] = 0

print("Copy:", copy_arr7)
print("Original after copy change:", original_arr7)


# ============================================================
# Task 8: Stacking and Splitting Arrays
# ============================================================
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([[9, 10]])

# 8.1 Vertical stack
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontal stack
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Combine with arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split into 3 equal parts
part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print("vstack_arr8_1:\n", vstack_arr8_1)
print("hstack_arr8_2:\n", hstack_arr8_2)
print("combined_arr8_3:\n", combined_arr8_3)
print("part1:\n", part1)
print("part2:\n", part2)
print("part3:\n", part3)


# ============================================================
# Task 9: Sorting and Searching
# ============================================================
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])

# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort each column independently
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find index where value 9 is present
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find index of maximum value
max_idx9_4 = np.argmax(arr9_1)

print("sorted_arr9_1:", sorted_arr9_1)
print("sorted_cols9_2:\n", sorted_cols9_2)
print("idx9_3:", idx9_3)
print("max_idx9_4:", max_idx9_4)

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[36 37 25 24 12]
 [46 16 30 18 48]]

--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
arr3_1:
 [[18  8  4  2  6]
 [10  4 18 12  2]
 [10  4 14 16 15]
 [ 8 14  8 16 13]]
arr3_2:
 [[18  0  0  0  0]
 [10  0 18 12  0]
 [10  0 14 16 15]
 [ 0 14  0 16 13]]
even_count3_3: 18

--- Task 4: Aggregation Functions ---
sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  